[build]
  command = "npm --prefix client install && npm --prefix client run build"
  publish = "client/dist"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"

[functions]
  directory = "client/netlify/functions"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
