[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION          = "20"
  NPM_CONFIG_PRODUCTION = "false"

[functions]
  directory = "client/netlify/functions"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
